old/dynamic/base/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.views.generic import DetailView,ListView

from base.models import CaseSet

urlpatterns =patterns('',
                      ( r'^case-set/(?P<pk>\d+)/?$',
                        DetailView.as_view(model=CaseSet,context_object_name="caseset")),
                      )

old/dynamic/corpora/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.views.generic import DetailView,ListView

from corpora.models import Corpus,Text
from corpora.views import AlphaParserView,TextView

urlpatterns =patterns('',
                      ( r'^/?$',
                        ListView.as_view(queryset=Corpus.objects.order_by('name'),
                                         context_object_name="corpus_list")),
                      ( r'^corpus/(?P<pk>\d+)/?$',
                        DetailView.as_view(model=Corpus,context_object_name="corpus")),
                      ( r'^text/(?P<pk>\d+)/?$',
                        TextView.as_view(model=Text,context_object_name="text")),
                      ( r'^text/(?P<text_id>\d+)/alpha_parser/?$',
                        AlphaParserView.as_view()),
                      )

  # r'^text/(?P<pk>\d+)/alpha_parser/?$'
  # r'^text/(?P<pk>\d+)/alpha_token/?$'
  # r'^text/(?P<pk>\d+)/morphological_parser/?$'
  # r'^text/(?P<pk>\d+)/morphological_token/?$'
  # r'^text/(?P<pk>\d+)/syntax_parser/?$'

old/dynamic/corpora/models.py
from django.db import models
from django.conf import settings

# Create your models here.

from languages.models import Language
from base.models import AbstractNameDesc

class Author(models.Model):
    name = models.CharField(max_length=1024,db_index=True)

    def __unicode__(self): return(self.name)

class Corpus(AbstractNameDesc):
    language = models.ForeignKey(Language)
    def get_absolute_url(self):
        return "/%s/corpus/%d" % ("corpora",self.id)

    class Meta:
        verbose_name_plural = 'corpora'

class Text(models.Model):
    corpus = models.ForeignKey(Corpus)
    author = models.ForeignKey(Author)
    title = models.CharField(max_length=1024)
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=False)
    
    def __unicode__(self): return(self.title)

    def get_absolute_url(self):
        return "/%s/text/%d" % ("corpora",self.id)

    def length(self):
        L=len(self.text)
        return(L)

    def text_br(self):
        l=self.text.split('\n')
        t='[br/]'.join(l)
        return(t)

class WDConcorso(models.Model):
    title = models.CharField(max_length=1024)
    tag = models.CharField(max_length=10,db_index=True)

    def __unicode__(self): return("["+self.tag+"] "+self.title)

    class Meta:
        verbose_name_plural = 'Wd concorsi'

class WDForum(models.Model):
    title = models.CharField(max_length=1024)
    wd_id = models.IntegerField()

    def __unicode__(self): return(self.title)
    
class WDAuthor(Author):
    wd_id = models.IntegerField()

class WDText(Text):
    concorso = models.ForeignKey(WDConcorso)
    forum = models.ForeignKey(WDForum)
    wd_id = models.IntegerField()

    def __unicode__(self): return(unicode(self.text))
    
    def get_absolute_url(self):
        return self.text.get_absolute_url()

    def get_wd_url(self):
        lab=self.title.lower().replace(" ","-")
        return "http://www.writersdream.org/forum/topic/%d-%s" % (self.wd_id,lab)

    def get_wd_tag(self): return(self.concorso.tag)

old/dynamic/corpora/views.py
# Create your views here.
from django.shortcuts import render_to_response,get_object_or_404
from django.template import RequestContext
from django.conf import settings
from django.shortcuts import render
from django.views.generic.base import View
from django.views.generic import DetailView

from corpora.models import *
from base.models import MARKERS,NEW_LINES

import re,time

def replace_newline(S,repl,preserve=False):
    if not preserve:
        for (r,n) in NEW_LINES:
            S=S.replace(n,repl)
        return(S)
    for (r,n) in NEW_LINES:
        S=S.replace(n,r+repl)
    return(S)

LF_IMG='<img src="/lf.png"/>'
END_IMG='<img src="/end.png"/>'
BEGIN_IMG='<img src="/begin.png"/>'

class TextView(DetailView):
    def get_context_data(self, **kwargs):
        context = super(TextView, self).get_context_data(**kwargs)
        context.update({'phase_text': True})
        return context

class AlphaParserView(View):
    #def get(self, request, text_id):
    #    text=get_object_or_404(Text,id=text_id)
    #    return render(request,"corpora/text_detail.html",{"text": text})

    def get(self,request,text_id):
        t0=time.time()
        text=get_object_or_404(Text,id=text_id)
        regexp_set=text.corpus.language.token_regexp_set
        c=re.compile(regexp_set.regexp_all())
        tokens=filter(bool,c.split(text.text))
        rexp_list=regexp_set.regexp_objects()

        L=len(tokens)
        t1=time.time()
        print "prima fase ok numtok=%d, sec.=%4.4f" % (L,t1-t0)

        def f(t):
            for (name,label,bg,fg,rexp,rexp_t) in rexp_list:
                if rexp.match(t):
                    T='<span class="'+label+'"> '
                    t=t.replace(" ","&nbsp;")
                    t=replace_newline(t," "+LF_IMG+"<br/>\n")
                    T+=t
                    T+="</span>"
                    return(T)
            if t[0]=='[':
                if t[1]=="/":
                    m=t[2:-1]
                    T='<img src="'+settings.CLOTILDE_ICONS_MARKERS_PATH+'/'+m+'.png"/>'
                    T+=END_IMG
                else:
                    m=t[1:-1]
                    T=BEGIN_IMG
                    T+='<img src="'+settings.CLOTILDE_ICONS_MARKERS_PATH+'/'+m+'.png"/>'
                if m in MARKERS:
                    return(T)
            t=t.replace(" ","&nbsp;")
            t=replace_newline(t," "+LF_IMG+"<br/>\n")
            T='<span class="not-found"> '
            T+=t
            T+="</span>"
            return(T)
        
        newtext=""
        n=1
        for t in tokens:
            ta=time.time()
            newtext+=f(t)
            tb=time.time()
            print "%d/%d %4.4f" % (n,L,tb-ta)
            n+=1
        t2=time.time()
        print "seconda fase ok - sec.=%4.4f" % (t2-t1)
        t3=time.time()
        print "terza fase ok - sec.=%4.4f" % (t3-t2)
        params={}
        params["rexp_list"]=rexp_list
        # aggiungere style per not-found (name=not matched)
        # 
        # span.not-found {
        #     color: #ffffff;
        #     background-color: #900000;
        #     border-left: 1px solid #ffffff;
        #     padding-right: 1em;
        # }

        params["style_list"]=map(lambda (name,label,bg,fg,rexp,rexp_t): (name+': '+rexp_t,label,fg,bg),rexp_list)
        params["text"]=text
        params["regexp_set"]=regexp_set
        params["newtext"]=newtext
        params["phase_alpha_p"]=True
        return render_to_response("corpora/text_detail_alpha_parsed.html", context=params)




# def alpha_parser(request,text_id):
#     t0=time.time()
#     text=get_object_or_404(Text,id=text_id)
#     regexp_set=text.corpus.language.token_regexp_set
#     c=re.compile(regexp_set.regexp_all())
#     tokens=filter(bool,c.split(text.text))
#     rexp_list=regexp_set.regexp_objects()

#     L=len(tokens)
#     t1=time.time()
#     print "prima fase ok numtok=%d, sec.=%4.4f" % (L,t1-t0)

#     def f(t):
#         for (name,label,bg,fg,rexp,rexp_t) in rexp_list:
#             if rexp.match(t):
#                 T='<span class="'+label+'"> '
#                 t=t.replace(" ","&nbsp;")
#                 t=replace_newline(t," "+LF_IMG+"<br/>\n")
#                 T+=t
#                 T+="</span>"
#                 return(T)
#         if t[0]=='[':
#             if t[1]=="/":
#                 m=t[2:-1]
#                 T='<img src="'+settings.CLOTILDE_ICONS_MARKERS_PATH+'/'+m+'.png"/>'
#                 T+=END_IMG
#             else:
#                 m=t[1:-1]
#                 T=BEGIN_IMG
#                 T+='<img src="'+settings.CLOTILDE_ICONS_MARKERS_PATH+'/'+m+'.png"/>'
#             if m in MARKERS:
#                 return(T)
#         t=t.replace(" ","&nbsp;")
#         t=replace_newline(t," "+LF_IMG+"<br/>\n")
#         T='<span class="not-found"> '
#         T+=t
#         T+="</span>"
#         return(T)
        
#     newtext=""
#     n=1
#     for t in tokens:
#         ta=time.time()
#         newtext+=f(t)
#         tb=time.time()
#         print "%d/%d %4.4f" % (n,L,tb-ta)
#         n+=1
#     t2=time.time()
#     print "seconda fase ok - sec.=%4.4f" % (t2-t1)
#     t3=time.time()
#     print "terza fase ok - sec.=%4.4f" % (t3-t2)
#     params={}
#     params["rexp_list"]=rexp_list
#     params["style_list"]=map(lambda (name,label,bg,fg,rexp,rexp_t): (name+': '+rexp_t,label,fg,bg),rexp_list)
#     params["text"]=text
#     params["regexp_set"]=regexp_set
#     params["newtext"]=newtext
#     return render_to_response("corpora/text_detail_parsed.html", params,
#                               context_instance=RequestContext(request))

def alpha_token(request,text_id):
    t0=time.time()
    text=get_object_or_404(Text,id=text_id)
    language=text.corpus.language
    regexp_set=language.token_regexp_set
    c=re.compile(regexp_set.regexp_all())
    tokens=list(set(filter(bool,c.split(text.text))))
    tokens.sort()
    rexp_list=regexp_set.regexp_objects()

    L=len(tokens)
    t1=time.time()
    print "prima fase ok numtok=%d, sec.=%4.4f" % (L,t1-t0)

    def f(t):
        for (name,label,bg,fg,rexp,rexp_t) in rexp_list:
            if rexp.match(t):
                t=t.replace(" ","&nbsp;")
                t=replace_newline(t," "+LF_IMG+"<br/>\n")
                return(label,name,t)
        if t[0]=='[':
            if t[1]=="/":
                m=t[2:-1]
                T='<img src="'+settings.CLOTILDE_ICONS_MARKERS_PATH+'/'+m+'.png"/>'
                T+=END_IMG
            else:
                m=t[1:-1]
                T=BEGIN_IMG
                T+='<img src="'+settings.CLOTILDE_ICONS_MARKERS_PATH+'/'+m+'.png"/>'
            if m in MARKERS:
                return("marker","marker",T)
        t=t.replace(" ","&nbsp;")
        t=replace_newline(t," "+LF_IMG+"<br/>\n")
        return("not-found","not found",t)
        
    token_list=[]
    n=1
    for t in tokens:
        ta=time.time()
        token_list.append(f(t))
        tb=time.time()
        print "%d/%d %4.4f" % (n,L,tb-ta)
        n+=1
    t2=time.time()
    print "seconda fase ok - sec.=%4.4f" % (t2-t1)
    t3=time.time()
    print "terza fase ok - sec.=%4.4f" % (t3-t2)
    params={}
    params["rexp_list"]=rexp_list
    params["style_list"]=map(lambda (name,label,bg,fg,rexp,rexp_t): (name+': '+rexp_t,label,fg,bg),rexp_list)
    params["text"]=text
    params["regexp_set"]=regexp_set
    params["token_list"]=token_list
    params["rowtemplate"]="corpora/includes/alpha_token_rows.html"
    return render_to_response("corpora/text_detail_token.html", context=params)

old/templates/original/corpora/corpus_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} - {{ application }} {{ corpus }}{% endblock %}

{% block content %}

<div id="largecontent">
<h1>{{ corpus }}</h1>

<p class="subtitle">{{ corpus.language }}</p>

<p>{{ corpus.description }}</p>
<table class="index">
  <tr><th colspan="2">&nbsp;</th><th>author</th><th>length</th><th colspan="2">date</th></tr>
  {% for l in corpus.text_set.all %}
  <tr>
    <td class="icon"><a href="{{ l.get_absolute_url }}"><img src="{{ ICON_TEXT }}"/></a></td>
    <td><a href="{{ l.get_absolute_url }}">{{ l }}</a></td>
    <td class="info center">{{ l.author }}</td>
    <td class="info center">{{ l.length }}</td>
    <td class="info right">{{ l.pub_date|date:"j b Y" }}</td>
    <td class="info center">{{ l.pub_date|time:"H:i" }}</td>
  </tr>
  {% endfor %}
</table>

</div>

{% endblock %}

old/templates/original/corpora/corpus_list.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} - {{ application }} {{ object.title }}{% endblock %}

{% block centercontent %}

<h1>Corpus</h1>

<ul>
{% for c in corpus_list %}
<li><a href="{{ c.get_absolute_url }}">{{ c }}</a> ({{ c.language }})</li>
{% endfor %}
</ul>


{% endblock %}

old/templates/original/corpora/text_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load santa_clara_editor %}
{% block title %} - {{ application }} {{ text }}{% endblock %}

{% block centercontent %}

<h1>{{ text }}</h1>

<p class="subtitle">{{ text.author }}, {{ text.pub_date|date:"j b Y" }} {{ text.pub_date|time:"H:i" }}, {{ text.length }} characters</p>
<div class="text">
{% block output %}
{{ text.text_br|santa_clara_lang }}
{% endblock %}
</div>
{% endblock %}

{% block applicationmenu %}
<ul>
  <li><a href="{{ text.get_absolute_url }}/"><i class="icon-circle{% if not phase_text %}-blank{% endif %}"></i> Text</a></li>
  <li><a href="{{ text.get_absolute_url }}/alpha_parser/"><i class="icon-circle{% if not phase_alpha_p %}-blank{% endif %}"></i> Alpha parser</a></li>
  <li><a href="{{ text.get_absolute_url }}/alpha_token/"><i class="icon-circle{% if not phase_alpha_t %}-blank{% endif %}"></i> Alpha token list</a></li>
  <li><a href="{{ text.get_absolute_url }}/morphological_parser/"><i class="icon-circle{% if not phase_morph_p %}-blank{% endif %}"></i> Morphological parser</a></li>
  <li><a href="{{ text.get_absolute_url }}/morphological_token/"><i class="icon-circle{% if not phase_morph_t %}-blank{% endif %}"></i> Morphological token list</a></li>
  <li><a href="{{ text.get_absolute_url }}/syntax_parser/"><i class="icon-circle{% if not phase_syntax_p %}-blank{% endif %}"></i> Syntax parser</a></li>
</ul>
{% endblock %}

old/templates/original/corpora/text_detail_alpha_parsed.html
{% extends "corpora/text_detail.html" %}
{% load i18n %}

{% block css %}
<style>
{% for name,label,fg,bg in style_list %}
span.{{ label }} {
    color: {{ fg }};
    background-color: {{ bg }};
    border-left: 1px solid {{ fg }};
    padding-right: 1em;
}
{% endfor %}

span.not-found {
    color: #ffffff;
    background-color: #900000;
    border-left: 1px solid #ffffff;
    padding-right: 1em;
}
</style>
{% endblock %} 

{% block output %}

{% block legend %}
<ul>
{% for name,label,fg,bg in style_list %}
<li><span style="color: {{ fg }};background-color: {{ bg }};">{{ name }}</span></li>
{% endfor %}
<li><span style="color: #ffffff;background-color: #900000;">not matched</span></li>
</ul>
{% endblock %}

{% block outputview %}
<div class="text">{{ newtext|safe }}</div>
{% endblock %}

{% endblock %}