old/dynamic/base/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.views.generic import DetailView,ListView

from base.models import CaseSet

urlpatterns =patterns('',
                      ( r'^case-set/(?P<pk>\d+)/?$',
                        DetailView.as_view(model=CaseSet,context_object_name="caseset")),
                      )

old/dynamic/languages/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.views.generic import DetailView,ListView

from languages.models import Language

urlpatterns =patterns('',
                      ( r'^/?$',
                        ListView.as_view(queryset=Language.objects.order_by('name'),
                                         context_object_name="language_list")),
                      ( r'^language/(?P<pk>\d+)/?$',
                        DetailView.as_view(model=Language,context_object_name="language")),
                      )

old/dynamic/languages/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.exceptions import ValidationError
from django.db.models.signals import post_save

from base.models import AbstractName,TokenRegexpSet,CaseSet,TokenRegexp,AlphabeticOrder,NEW_LINES
from morphology.models import NotWord

# Create your models here.


class Language(AbstractName):
    token_regexp_set = models.ForeignKey(TokenRegexpSet)
    case_set = models.ForeignKey(CaseSet,default=1)
    period_sep = models.ForeignKey(TokenRegexp)
    alphabetic_order = models.ForeignKey(AlphabeticOrder)

    def clean(self):
        if not self.token_regexp_set.has_regexp(self.period_sep):
            raise ValidationError('Period regexp must be in language token regexp set')
        models.Model.clean(self)

    def __unicode__(self): return(self.name)

    def has_case(self):
        return(self.case_set.length()!=0)

    def token_regexp_expression(self):
        return(self.token_regexp_set.regexp_all())


    def get_absolute_url(self):
        return( "/languages/language/%d" % self.id )

    def part_of_speech_set(self):
        return(PartOfSpeech.objects.by_language(self))

    def derivation_set(self):
        return(Derivation.objects.by_language(self))

def insert_newlines_as_notword(sender,instance,created,**kwargs):
    for (r,n) in NEW_LINES: 
        NotWord.objects.get_or_create(language=instance,name="new line ("+r+")",word=n)

post_save.connect(insert_newlines_as_notword,sender=Language)

old/dynamic/languages/views.py
# Create your views here.

old/templates/clotilde/languages/caseset_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} - {{ application }} {{ caseset }}{% endblock %}

{% block content %}

<div id="largecontent">
<h1>{{ caseset }}</h1>

<h2>Languages:</h2>

<ul>
{% for l in caseset.language_set.all %}
<li>{{ l }}</li>
{% endfor %}
</ul>

<h2>Pairs:</h2>

<table>
<tr>
{% for p in caseset.pairs.all %}
<td>{{ p }}{% autoescape off %}{% cycle "</td>" "</td>" "</td>" "</td>" "</td>" "</td>" "<td></tr><tr>" %}{% endautoescape %}
{% endfor %}
</tr>
</table>
</div>

{% endblock %}

old/templates/clotilde/languages/language_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} - {{ application }} {{ language }}{% endblock %}

{% block content %}

<div id="largecontent">
<h1>{{ language }}</h1>

<p class="subtitle">{% if language.has_case %}<a href="{{ language.case_set.get_absolute_url }}">Bicase script: {{ language.case_set }}</a>
{% else %}Unicase script{% endif %}</p>

<h2>Base rules</h2>

<h3>Regexp: {{ language.token_regexp_set }}</h3>

<table>
{% with language.period_sep as t %}
<tr><td colspan=2 class="right">Period separator:</td><td>{% if t.disabled %}disabled{% endif %}</td><td>{{ t.regexp }}</td></tr>
{% endwith %}
{% for t in language.token_regexp_set.tokenregexpsetthrough_set.all %}
<tr style="color: {{ t.fg_color }};background-color: {{ t.bg_color }}">
  <td>{{ t.order }}</td><td class="right">{{ t.name }}:</td><td>{% if t.disabled %}disabled{% endif %}</td><td>{{ t.regexp }}</td>
</tr>
{% endfor %}
</table>

<h3>Capitalized Word</h3>

<table>
{% for cw in language.capitalizedword_set.all %}
<tr>
  <td class="right">{{ cw.part_of_speech }}:</td><td>{{ cw.classification }}</td>
</tr>
{% endfor %}
</table>

<h3>Part of speech</h3>

<table>
{% for p in language.part_of_speech_set.all %}
<tr><td>{{ p }}</td><td>{% if p.is_inflected %}inflected</td>
  <td>{% for cat,elist in p.get_classifications_dict %}{{ cat }}: {% for e in elist %}{{ e }}{% if forloop.last %}{% else %}, {% endif %}{% endfor %}{% if forloop.last %}{% else %}; {% endif %}{% endfor %}{% else %}invariant</td><td>{% endif %}</td></tr>
{% endfor %}
</table>


<h2>Derivation rules</h2>

<table>
<tr class="borderbottom"><th>&nbsp;</th><th>from</th>
  <th>to</th><th colspan="3">transformation</th><th>paradigma</th></tr>
{% for d in language.derivation_set.all %}
<tr>
  <th class="column left">{{ d }}</th>
  <td>{{ d.root_part_of_speech }}</td>
  <td>{{ d.dst_part_of_speech }}</td>
  <td rowspan="2">{{ d.regexp.pattern }}</td><td rowspan="2">=></td><td rowspan="2">{{ d.regexp.replacement }}</td>
  <td  rowspan="2"><a href="{{ d.paradigma.get_absolute_url }}">{{ d.paradigma }}</a></td>
</tr>
<tr class="borderbottom">
  <th>{% if d.productive %}&nbsp;{% else %}not productive{% endif %}</th>
  <td class="tiny">{{ d.get_root_classifications }}</td>
  <td class="tiny">{{ d.get_classifications }}</td>
</tr>

{% endfor %}
</table>

<h2>Morphological rules</h2>

<h3>Paradigmas</h3>

<ul>
{% for p in language.paradigma_set.all %}
{% if p.part_of_speech.is_inflected %}
<li><a href="{{ p.get_absolute_url }}">{{ p }}</a></li>
{% endif %}
{% endfor %}
</ul>

</div>

{% endblock %}